export const Explornation = () => {
  return (
    <div id="elem">
      <table border={1}>
        <tr>
          <th>要素</th>
          <th>要素の説明</th>
          <th>単位</th>
        </tr>
        <tr>
          <th>TTD</th>
          <td>湿数</td>
          <td>K</td>
        </tr>
          <tr>
          <th>RH</th>
          <td>湿度</td>
          <td>％</td>
        </tr>
        <tr>
          <th>OMG</th>
          <td>鉛直流</td>
          <td>hpa/h</td>
        </tr>
        <tr>
          <th>PSEA</th>
          <td>海面気圧</td>
          <td>hpa</td>
        </tr>
        <tr>
          <th>WIND_F</th>
          <td>風速</td>
          <td>m/s</td>
          
        </tr>
        <tr>
          <th>WIND_D</th>
          <td>風向</td>
          <td>度</td>
          
        </tr>
        <tr>
          <th>VOR</th>
          <td>渦度</td>
          <td>10（-6）/s</td>
        </tr>
        <tr>
          <th>CONV</th>
          <td>収束</td>
          <td>10（-6）/s</td>
        </tr>
        <tr>
          <th>SP</th>
          <td>シアーパラメーター</td>
          <td>10（-6）/s</td>
        </tr>
        <tr>
          <th>EPT</th>
          <td>相当温位（bolton1980）</td>
          <td>K</td>
        </tr>
        <tr>
          <th>TADV</th>
          <td>温度移流（水平方向）</td>
          <td>K/h</td>
        </tr>
        <tr>
          <th>P</th>
          <td>気圧</td>
          <td>hpa</td>
        </tr>
        <tr>
          <th>FLWV</th>
          <td>水蒸気フラックス</td>
          <td>g/m2/s</td>
        </tr>
        <tr>
          <th>EL</th>
          <td>平衡高度</td>
          <td>m</td>
        </tr>
        <tr>
          <th>DLFC</th>
          <td>自由対流高度までの距離</td>
          <td>m</td>
        </tr>
        <tr>
          <th>SREH</th>
          <td>ストームに相対的なヘリシティ </td>
          <td>m2/s2</td>
        </tr>
        <tr>
          <th>BAND</th>
          <td>線状降水帯6条件</td>
          <td>6条件</td>
        </tr>
        <tr>
          <th>KI</th>
          <td>k-index(850,700,500hPa)</td>
          <td>K</td>
        </tr>
        <tr>
          <th>KI+</th>
          <td>k-index(925,700,600hPa)</td>
          <td>K</td>
        </tr>
        <tr>
          <th>SSI8550</th>
          <td>SSI(850,500hPa)</td>
          <td>℃</td>
        </tr>
        <tr>
          <th>SWEAT</th>
          <td>シビアウェザー指数</td>
        </tr>
        <tr>
          <th>TPW</th>
          <td>可降水量</td>
          <td>kg/m2</td>
        </tr>
        <tr>
          <th>TT</th>
          <td>トータルトータルズ</td>
          <td>℃</td>
        </tr>
        <tr>
          <th>VWS_F</th>
          <td>鉛直シアーの大きさ（950,700hpa)</td>
          <td>m/s</td>
        </tr>
        <tr>
          <th>VWS_D</th>
          <td>鉛直シアーの向き（950,700hpa)</td>
          <td>度</td>
        </tr>
        <tr>
          <th>SEPT-EPT</th>
          
          <td>700_500hpa最小飽和相当温位-850hPa以下の最大相当温位</td>
          <td>K</td>
        </tr>
        <tr>
          <th>対流不安定度</th>
          <td>(700_500hpa最小相当温位-1000_850hPaの最大相当温位)/(最小相当温位の気圧-最大相当温位の気圧)*(-100)</td>
          <td>K/100hPa</td>
        </tr>
      </table>
    </div>
  )
}
